### ISSUE TITLE
Multi Mode Support

### ISSUE THREAD

**Issue by ssayer** [whomwah/rqrcode_core#23]
We have a [use case](https://spec.smarthealth.cards/#encoding-chunks-as-qr-codes) for supporting multi-mode encoded QR codes. We've already used RQRCode to build a hacky implementation by overriding some of the `RQRCodeCore::QRCode` methods and creating a custom encoder class. We're interested in making this feature more robust and contributing it back to rqrcode_core, but wanted to gauge your interest and discuss the necessary API changes first.

See @radamson example below.

**Comment by whomwah** [comment]
Hi guys, this sounds interesting. I didn't know mixed modes was actually a thing. Is this part of the QR Code spec, or just a hack to fit more data into an encoding?

> We've already used RQRCode to build a hacky implementation by overriding some of the RQRCodeCore::QRCode methods and creating a custom encoder class

Is this public, can I see it? In terms of any additions to this lib, the most import thing for me right now is backwards compatibility.

**Comment by ssayer** [comment]
Mixed Modes are allowed by the spec (section 7.3.7). In our use case, the mixed modes are used to denote the position of a QR code in a sequence of codes along with the actual data "chunk" encoded in the image. When the "chunks" are assembled in sequence they can be used to reconstruct a larger payload.

Our repository is located at https://github.com/dvci/health_cards. Specifically you'll want to look at [`lib/health_cards/chunk.rb`](https://github.com/dvci/health_cards/blob/main/lib/health_cards/chunk.rb) which is our shim around RQRCode. `SHCQRCode` is our custom encoder that uses both byte and numeric encoding. We can genericize that code to handle multiple different encoding types.

This should be backwards compatible. The code would only be used when the input is a Hash instead of a string. If you're concerned about existing users encoding Hashes (even though the spec says it should be a string), we could also require mode: :multi to be extra sure.

**Comment by whomwah** [comment]
Thanks for the info @ssayer. Let me take a look at all this and get back to you 👍

**Comment by ssayer** [comment]
@whomwah We've got some cycles coming up to get this done, so I wanted to check in see if you had a chance to take a look.

**Comment by whomwah** [comment]
Hi @ssayer, I've not forgotten, but only get to work on the project during work hours every couple of weeks as I don't have and spare time after hours. So I will be free Thu to look at this.

**Comment by ssayer** [comment]
Totally understand, thanks!

**Comment by whomwah** [comment]
@ssayer I've had a read though, and yes, I'd like the idea of adding this functionality. Currently the lib checks for a `String` to encode: https://github.com/whomwah/rqrcode_core/blob/master/lib/rqrcode_core/qrcode/qr_code.rb#L174-L176 so passing an `Array` in should be a nice optional addition.

Maybe if you get an PR up for further discussion?

**Comment by ssayer** [comment]
Sure thing, I'll get started on this today.

**Comment by whomwah** [comment]
✅
