### ISSUE TITLE
Memory allocation issue

### ISSUE THREAD

**Issue by dixpac** [whomwah/rqrcode_core#27]
Hey!

This [method](https://github.com/whomwah/rqrcode_core/blob/master/lib/rqrcode_core/qrcode/qr_util.rb#L78) allocates a lot of memory. In our app this method allocates more than 5MB per call.

Example:
<img width="1280" alt="Screenshot 2021-08-05 at 14 33 18" src="https://user-images.githubusercontent.com/7427365/128350540-45a599cc-eb3e-420f-b35a-6fa182aad361.png">

**Comment by whomwah** [comment]
Hey @dixpac thanks for the heads up. I don't suppose you have an example of how it could be improved?

**Comment by whomwah** [comment]
I have a draft PR @dixpac which "seems" to improve things with my limited knowledge of both bitwise and memory profiling. How were you able to nail it down to that specific method?

Here's the draft PR. I wonder if you could try it your end to see if you get any improvement?
https://github.com/whomwah/rqrcode_core/pull/28

**Comment by dixpac** [comment]
Sadly I don't, since I don't know codebase that much, but I'm willing to help.

Yes I will try you changes thank you ❤️ 

I've run memory-profiler, to be exact rack-mini-profiler with `?pp=profile-memory` on our request that renders qr. 
Memory profiler report showed exact line number that allocates the most
